(historic = 'no' OR historic IS NULL)
AND

(other_tags IS NULL
OR (
other_tags NOT LIKE '%"abandoned"=>"yes"%'
AND other_tags NOT LIKE '%"disused"=>"yes"%'
AND other_tags NOT LIKE '%"disused"=>"yes"%'
AND other_tags NOT LIKE '%"razed"=>"yes"%'
AND other_tags NOT LIKE '%"ruins"=>"yes"%'
AND other_tags NOT LIKE '%"ruined"=>"yes"%'
AND other_tags NOT LIKE '%"demolished"=>"yes"%'
AND other_tags NOT LIKE '%"removed"=>"yes"%'
AND other_tags NOT LIKE '%"ruined"=>"yes"%'
AND other_tags NOT LIKE '%"destroyed"=>"yes"%'
AND other_tags NOT LIKE '%"status"=>"abandoned"%'

AND other_tags NOT LIKE '%"abandoned:industrial"=>"mine"%'
AND other_tags NOT LIKE '%"disused:industrial"=>"mine"%'
AND other_tags NOT LIKE '%"razed:industrial"=>"mine"%'
AND other_tags NOT LIKE '%"ruins:industrial"=>"mine"%'
AND other_tags NOT LIKE '%"demolished:industrial"=>"mine"%'
AND other_tags NOT LIKE '%"removed:industrial"=>"mine"%'
AND other_tags NOT LIKE '%"ruined:industrial"=>"mine"%'
AND other_tags NOT LIKE '%"destroyed:industrial"=>"mine"%'
AND other_tags NOT LIKE '%"old:industrial"=>"mine"%'
AND other_tags NOT LIKE '%"was:industrial"=>"mine"%'

AND other_tags NOT LIKE '%"abandoned:industrial"=>"solution_mine"%'
AND other_tags NOT LIKE '%"disused:industrial"=>"solution_mine"%'
AND other_tags NOT LIKE '%"razed:industrial"=>"solution_mine"%'
AND other_tags NOT LIKE '%"ruins:industrial"=>"solution_mine"%'
AND other_tags NOT LIKE '%"demolished:industrial"=>"solution_mine"%'
AND other_tags NOT LIKE '%"removed:industrial"=>"solution_mine"%'
AND other_tags NOT LIKE '%"ruined:industrial"=>"solution_mine"%'
AND other_tags NOT LIKE '%"destroyed:industrial"=>"solution_mine"%'
AND other_tags NOT LIKE '%"old:industrial"=>"solution_mine"%'
AND other_tags NOT LIKE '%"was:industrial"=>"solution_mine"%'

AND other_tags NOT LIKE '%"abandoned:landuse"=>"mine"%'
AND other_tags NOT LIKE '%"disused:landuse"=>"mine"%'
AND other_tags NOT LIKE '%"razed:landuse"=>"mine"%'
AND other_tags NOT LIKE '%"ruins:landuse"=>"mine"%'
AND other_tags NOT LIKE '%"demolished:landuse"=>"mine"%'
AND other_tags NOT LIKE '%"removed:landuse"=>"mine"%'
AND other_tags NOT LIKE '%"ruined:landuse"=>"mine"%'
AND other_tags NOT LIKE '%"destroyed:landuse"=>"mine"%'
AND other_tags NOT LIKE '%"old:landuse"=>"mine"%'
AND other_tags NOT LIKE '%"was:landuse"=>"mine"%'

AND other_tags NOT LIKE '%"abandoned:landuse"=>"mine_spoils"%'
AND other_tags NOT LIKE '%"disused:landuse"=>"mine_spoils"%'
AND other_tags NOT LIKE '%"razed:landuse"=>"mine_spoils"%'
AND other_tags NOT LIKE '%"ruins:landuse"=>"mine_spoils"%'
AND other_tags NOT LIKE '%"demolished:landuse"=>"mine_spoils"%'
AND other_tags NOT LIKE '%"removed:landuse"=>"mine_spoils"%'
AND other_tags NOT LIKE '%"ruined:landuse"=>"mine_spoils"%'
AND other_tags NOT LIKE '%"destroyed:landuse"=>"mine_spoils"%'
AND other_tags NOT LIKE '%"old:landuse"=>"mine_spoils"%'
AND other_tags NOT LIKE '%"was:landuse"=>"mine_spoils"%'

AND other_tags NOT LIKE '%"abandoned:landuse"=>"quarry"%'
AND other_tags NOT LIKE '%"disused:landuse"=>"quarry"%'
AND other_tags NOT LIKE '%"razed:landuse"=>"quarry"%'
AND other_tags NOT LIKE '%"ruins:landuse"=>"quarry"%'
AND other_tags NOT LIKE '%"demolished:landuse"=>"quarry"%'
AND other_tags NOT LIKE '%"removed:landuse"=>"quarry"%'
AND other_tags NOT LIKE '%"ruined:landuse"=>"quarry"%'
AND other_tags NOT LIKE '%"destroyed:landuse"=>"quarry"%'
AND other_tags NOT LIKE '%"old:landuse"=>"quarry"%'
AND other_tags NOT LIKE '%"was:landuse"=>"quarry"%'

AND other_tags NOT LIKE '%"abandoned:man_made"=>"mineshaft"%'
AND other_tags NOT LIKE '%"disused:man_made"=>"mineshaft"%'
AND other_tags NOT LIKE '%"razed:man_made"=>"mineshaft"%'
AND other_tags NOT LIKE '%"ruins:man_made"=>"mineshaft"%'
AND other_tags NOT LIKE '%"demolished:man_made"=>"mineshaft"%'
AND other_tags NOT LIKE '%"removed:man_made"=>"mineshaft"%'
AND other_tags NOT LIKE '%"ruined:man_made"=>"mineshaft"%'
AND other_tags NOT LIKE '%"destroyed:man_made"=>"mineshaft"%'
AND other_tags NOT LIKE '%"old:man_made"=>"mineshaft"%'
AND other_tags NOT LIKE '%"was:man_made"=>"mineshaft"%'

AND other_tags NOT LIKE '%"abandoned:man_made"=>"adit"%'
AND other_tags NOT LIKE '%"disused:man_made"=>"adit"%'
AND other_tags NOT LIKE '%"razed:man_made"=>"adit"%'
AND other_tags NOT LIKE '%"ruins:man_made"=>"adit"%'
AND other_tags NOT LIKE '%"demolished:man_made"=>"adit"%'
AND other_tags NOT LIKE '%"removed:man_made"=>"adit"%'
AND other_tags NOT LIKE '%"ruined:man_made"=>"adit"%'
AND other_tags NOT LIKE '%"destroyed:man_made"=>"adit"%'
AND other_tags NOT LIKE '%"old:man_made"=>"adit"%'
AND other_tags NOT LIKE '%"was:man_made"=>"adit"%'

AND other_tags NOT LIKE '%"abandoned:man_made"=>"heap"%'
AND other_tags NOT LIKE '%"disused:man_made"=>"heap"%'
AND other_tags NOT LIKE '%"razed:man_made"=>"heap"%'
AND other_tags NOT LIKE '%"ruins:man_made"=>"heap"%'
AND other_tags NOT LIKE '%"demolished:man_made"=>"heap"%'
AND other_tags NOT LIKE '%"removed:man_made"=>"heap"%'
AND other_tags NOT LIKE '%"ruined:man_made"=>"heap"%'
AND other_tags NOT LIKE '%"destroyed:man_made"=>"heap"%'
AND other_tags NOT LIKE '%"old:man_made"=>"heap"%'
AND other_tags NOT LIKE '%"was:man_made"=>"heap"%'

AND other_tags NOT LIKE '%"abandoned:man_made"=>"spoil_heap"%'
AND other_tags NOT LIKE '%"disused:man_made"=>"spoil_heap"%'
AND other_tags NOT LIKE '%"razed:man_made"=>"spoil_heap"%'
AND other_tags NOT LIKE '%"ruins:man_made"=>"spoil_heap"%'
AND other_tags NOT LIKE '%"demolished:man_made"=>"spoil_heap"%'
AND other_tags NOT LIKE '%"removed:man_made"=>"spoil_heap"%'
AND other_tags NOT LIKE '%"ruined:man_made"=>"spoil_heap"%'
AND other_tags NOT LIKE '%"destroyed:man_made"=>"spoil_heap"%'
AND other_tags NOT LIKE '%"old:man_made"=>"spoil_heap"%'
AND other_tags NOT LIKE '%"was:man_made"=>"spoil_heap"%'

AND other_tags NOT LIKE '%"abandoned:man_made"=>"tailings_pond"%'
AND other_tags NOT LIKE '%"disused:man_made"=>"tailings_pond"%'
AND other_tags NOT LIKE '%"razed:man_made"=>"tailings_pond"%'
AND other_tags NOT LIKE '%"ruins:man_made"=>"tailings_pond"%'
AND other_tags NOT LIKE '%"demolished:man_made"=>"tailings_pond"%'
AND other_tags NOT LIKE '%"removed:man_made"=>"tailings_pond"%'
AND other_tags NOT LIKE '%"ruined:man_made"=>"tailings_pond"%'
AND other_tags NOT LIKE '%"destroyed:man_made"=>"tailings_pond"%'
AND other_tags NOT LIKE '%"old:man_made"=>"tailings_pond"%'
AND other_tags NOT LIKE '%"was:man_made"=>"tailings_pond"%'

AND other_tags NOT LIKE  '%"abandoned"=>"quarry"%'
AND other_tags NOT LIKE  '%"abandoned:quarry"=>"yes"%'
AND other_tags NOT LIKE  '%"abandoned:amenity"=>"quarry"%'
AND other_tags NOT LIKE  '%"description"=>"Abandoned quarry"%'
AND other_tags NOT LIKE  '%"description"=>"abandoned mine"%'
AND other_tags NOT LIKE  '%"quarry"=>"abandoned"%'
AND other_tags NOT LIKE  '%"state"=>"abandoned"%'
AND other_tags NOT LIKE  '%"abandoned:building"=>"yes","industrial"=>"mine"%'
AND other_tags NOT LIKE  '%"abandoned:landuse"=>"abandoned:quarry"%'
AND other_tags NOT LIKE  '%"abandoned:landuse"=>"yes"%'
AND other_tags NOT LIKE  '%"operational_status"=>"abandoned"%'
AND other_tags NOT LIKE  '%"operator"=>"Abandoned"%'
AND other_tags NOT LIKE  '%"abandoned:amenity"=>"prison_camp"%'

AND other_tags NOT LIKE  '%"designation"=>"Disused"%'
AND other_tags NOT LIKE  '%"disused"=>"quarry"%'
AND other_tags NOT LIKE  '%"status"=>"disused"%'
AND other_tags NOT LIKE  '%"state"=>"disused"%'
AND other_tags NOT LIKE  '%"description"=>"Disused %'
AND other_tags NOT LIKE  '%"disused"=>"landuse"%'
AND other_tags NOT LIKE  '%"disused"=>"landuse=quarry"%'
AND other_tags NOT LIKE  '%"disused"=>"y"%'
AND other_tags NOT LIKE  '%"disused"=>"ye"%'
AND other_tags NOT LIKE  '%"disused"=>"yesw"%'
AND other_tags NOT LIKE  '%"disused:landuse"=>"yes"%'
AND other_tags NOT LIKE  '%"disused:quarry"=>"yes"%'
AND other_tags NOT LIKE  '%"disused:man_made"=>"quarry"%'
AND other_tags NOT LIKE  '%"operator"=>"disused"%'
AND other_tags NOT LIKE  '%"quarry"=>"disused"%'
AND other_tags NOT LIKE  '%"ruins"=>"building"%'
AND other_tags NOT LIKE  '%"abandoned:landuse"=>"landfill"%'
AND other_tags NOT LIKE  '%Abandoned Mine%'
AND other_tags NOT LIKE  '%"abandoned:landuse"=>"industrial"%'
AND other_tags NOT LIKE  '%"disused:landuse"=>"industrial"%'
AND other_tags NOT LIKE  '%"disused:building"=>"industrial"%'
AND other_tags NOT LIKE  '%"mineshaft_type"=>"disused"%'
AND other_tags NOT LIKE  '%"operator"=>"Disused"%'
AND other_tags NOT LIKE  '%"description"=>"Disused %'
AND other_tags NOT LIKE  '%"historic"=>"heritage"%'
AND other_tags NOT LIKE  '%"historic"=>"mine"%'
AND other_tags NOT LIKE  '%"historic"=>"yes"%'
AND other_tags NOT LIKE  '%"historic"=>"heritage"%'
AND other_tags NOT LIKE  '%"historic"=>"mine_shaft"%'

AND other_tags NOT LIKE  '%"abandoned:man_made"=>"mine%'
AND other_tags NOT LIKE  '%"operator"=>"abandoned"%'
AND other_tags NOT LIKE  '%"mine"=>"abandoned"%'
AND other_tags NOT LIKE  '%"description"=>"Abandoned%'
AND other_tags NOT LIKE  '%"condition"=>" abandoned "%'
AND other_tags NOT LIKE  '%"abandoned:military"=>"bunker"%'
AND other_tags NOT LIKE  '%"name:en"=>" abandoned adit"%'
AND other_tags NOT LIKE  '%"vent"=>"abandoned_mine_shaft"%'
AND other_tags NOT LIKE  '%"operator"=>"DEM (SA Gov) Abandoned"%'
AND other_tags NOT LIKE  '%"operator"=>"abandonned%'
AND other_tags NOT LIKE  '%"description"=>"abandoned%'
AND other_tags NOT LIKE  '%"abandoned:man_made"=>"yes"%'
AND other_tags NOT LIKE  '%"abandoned"=>"true"%'
AND other_tags NOT LIKE  '%"disused:leisure"=>"closed"%'
AND other_tags NOT LIKE  '%"disused:adit_type"=>"bomb_shelter"%'
AND other_tags NOT LIKE  '%"disused:military"=>"shelter"%'
AND other_tags NOT LIKE  '%"disused:amenity"=>"adit"%'
AND other_tags NOT LIKE  '%"disused:mine"=>"yes"%'
AND other_tags NOT LIKE  '%"disused"=>"amenity"%'
AND other_tags NOT LIKE  '%"disused:resource"=>"%'
AND other_tags NOT LIKE  '%"historic"=>"ruins"%'
AND other_tags NOT LIKE  '%"historic:period"%'
AND other_tags NOT LIKE  '%"historical_and_cultural_sites:level:CN"%'
AND other_tags NOT LIKE  '%"historic:civilization"%'
AND other_tags NOT LIKE  '%"historic"=>"tes"%'
AND other_tags NOT LIKE  '%"historic"=>"technical_monument"%'
AND other_tags NOT LIKE  '%"historic"=>"shelter"%'
AND other_tags NOT LIKE  '%"historic"=>"razed:mineshaft"%'
AND other_tags NOT LIKE  '%"historic"=>"mining"%'
AND other_tags NOT LIKE  '%"historic"=>"quarry"%'
AND other_tags NOT LIKE  '%"historic"=>"monument"%'
AND other_tags NOT LIKE  '%"historic"=>"mineshaft"%'
AND other_tags NOT LIKE  '%"historic"=>"mine_adit"%'
AND other_tags NOT LIKE  '%"historic"=>"industrial"%'
AND other_tags NOT LIKE  '%"historic"=>"bunker"%'
AND other_tags NOT LIKE  '%"historic"=>"military"%'
AND other_tags NOT LIKE  '%"historic"=>"building"%'
AND other_tags NOT LIKE  '%"historic"=>"boundary_stone"%'
AND other_tags NOT LIKE  '%"historic"=>"archaeological_site"%'
AND other_tags NOT LIKE  '%"historic"=>"adit"%'
AND other_tags NOT LIKE  '%"historic"=>"mine_level"%'
AND other_tags NOT LIKE  '%"attraction"=>"historic"%'
AND other_tags NOT LIKE  '%"heritage:operator"%'
AND other_tags NOT LIKE  '%"historic"=>"memorial"%'
AND other_tags NOT LIKE  '%"historic"=>"tunnel_entrance"%'
AND other_tags NOT LIKE  '%"archaeological_site"%'
AND other_tags NOT LIKE  '%"operator"=>"abandonned"%'
AND other_tags NOT LIKE  '%"historic"=>"quaary"%'
AND other_tags NOT LIKE  '%"historic"=>"tes"%'
AND other_tags NOT LIKE  '%"natural"=>"cave_entrance"%'
AND other_tags NOT LIKE  '%"end_date"%'

))